services:
  blazorclient:
    image: ${DNETBLAZOR_IMAGE:-ghcr.io/valdtechsso/dnetblazor:main}
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      datalnet:
       ipv4_address: 192.168.0.3
    ports:
      - "5001:80"
networks:
  datalnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
